### ISSUE TITLE
Python pre-commit issue (fix in comment)

### ISSUE THREAD

**Issue by hwrightson** [best-practice-and-impact/govcookiecutter#50]
Hello,

We set up a python project using govcookiecutter and `pyenv install 3.10.2` last week and encountered the following error: `ImportError: cannot import name '_unicodefun' from 'click'`. Relevant stackoverflow thread: https://stackoverflow.com/questions/71673404/importerror-cannot-import-name-unicodefun-from-click

The issue appears to be a library version issue which can be solved by updating a newer version of "black" in the pre-commit-config.yaml - I think 22.3.0. It might be prudent to update this so that other users don't encounter the same issue.

Many thanks, H

**Comment by ESKYoung** [comment]
Thanks for raising an issue @hwrightson, and for signposting a potential solution!

Maintenance of this repo was handed over to the ONS BPI team when I left @ukgovdatascience. Would you mind forking this repo, and raising a PR with your proposed changes?

Couple of thoughts with your proposed solution. The penultimate version `black` (22.1.0) was their first live (non-beta) release.

At some point, on or before this release, they made some changes to the way `black` does some of the formatting; you may have noticed this when upgrading to 22.3.0, and running the pre-commit hooks. This means it's likely that this repository, and possibly any downstream projects that are updated from this one (say using `cruft`), will need to be reformatted. The latter very much depends on the owner of those downstream projects!

I think the changes are small (say `1*1` becomes `1 * 1`), but it's worth bearing that they may be painful/annoying to implement for legacy downstream projects! The alternative, as proposed in your linked SO solution, is to pink `Click` to 8.0.2. This may not be ideal, and/or long-lasting solution, especially if vulnerabilities arise in `Click` or packages using it as a dependency.

If the team decides to go with upgrading `black`, it's worth pointing out this is potentially a breaking change in the release notes!

Tagging @alexander-newton and @Jacobb164 for visibility (if they're still at ONS!).

**Comment by Jacobb164** [comment]
This will be fixed with the next update which will be released 16/09/2022
